#
//  bug_report.yml
//  
//
//  Created by Musab Amin on 9/19/25.
//

name: Bug Report
about: Report a bug to help us improve the app.
title: "[Bug]: "
labels: ["Geofence Notifier", "bug"]

body:
  - type: dropdown
    id: app-name
    attributes:
      label: Which app is this issue for?
      description: Select the app where you found the bug.
      options:
        - Geofence Notifier
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide the steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
