#
//  config.yml
//  
//
//  Created by Musab Amin on 9/19/25.
//

blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/malrawi/AplosIT-Help-Desk/discussions
    about: Ask questions and discuss with other users.
